import {
  ModuleKey,
  InstitutionType,
} from "./modules";

const COMMON: ModuleKey[] = [
  "dashboard",
  "students",
  "teachers",
  "staff",
  "attendance",
  "notifications",
  "reports",
  "documents",
  "settings",
];

export const INSTITUTION_MODULES: Record<
  InstitutionType,
  ModuleKey[]
> = {
  PRIVATE_SCHOOL: [
    ...COMMON,
    "parents",
    "classes",
    "sections",
    "subjects",
    "homework",
    "assignments",
    "exams",
    "results",
    "fees",
    "timetable",
    "library",
    "transport",
    "certificates",
  ],

  SCHOOL: [
    ...COMMON,
    "parents",
    "classes",
    "sections",
    "subjects",
    "homework",
    "assignments",
    "exams",
    "results",
    "fees",
    "timetable",
    "library",
    "transport",
    "certificates",
  ],

  COLLEGE: [
    ...COMMON,
    "parents",
    "departments",
    "courses",
    "programs",
    "semesters",
    "subjects",
    "batches",
    "exams",
    "results",
    "fees",
    "assignments",
    "timetable",
    "library",
    "hostel",
    "transport",
    "certificates",
  ],

  UNIVERSITY: [
    ...COMMON,
    "departments",
    "courses",
    "programs",
    "semesters",
    "subjects",
    "batches",
    "exams",
    "results",
    "fees",
    "assignments",
    "timetable",
    "library",
    "hostel",
    "transport",
    "certificates",
    "research",
    "thesis",
  ],

  COACHING: [
    ...COMMON,
    "courses",
    "subjects",
    "batches",
    "exams",
    "results",
    "fees",
    "study-material",
    "assignments",
    "homework",
    "timetable",
    "certificates",
  ],

  TUITION: [
    ...COMMON,
    "subjects",
    "batches",
    "fees",
    "homework",
    "assignments",
    "exams",
    "results",
    "study-material",
    "timetable",
  ],

  INSTITUTE: [
    ...COMMON,
    "courses",
    "departments",
    "subjects",
    "batches",
    "exams",
    "results",
    "fees",
    "study-material",
    "assignments",
    "timetable",
    "certificates",
  ],

  OTHER: [
    ...COMMON,
    "courses",
    "subjects",
    "batches",
    "fees",
    "exams",
    "results",
    "assignments",
    "study-material",
    "certificates",
  ],
};